export const medicinesList = [
	{
		productId: 234981,
		name: 'Everherb Pharmeasy Moringa (Drum Stick) Immunity Booster Capsules Natural Multivitamin Bottle Of 60',
		slug: 'everherb-moringa-drum-stick---immunity-booster-capsules---natural-multivitamin---bottle-of-60-234981',
		manufacturer: 'EVERHERB',
		productType: 2,
		mrpDecimal: '599.00',
		salePriceDecimal: '275.54',
		discountDecimal: '323.46',
		discountPercent: '54',
		categoryId: null,
		damImages: [
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/H62199/everherb-pharmeasy-moringa-drum-stick-immunity-booster-capsules-natural-multivitamin-bottle-of-60-2-1687237313.jpg',
				face: 'front',
				sequence: '2',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/H62199/everherb-pharmeasy-moringa-drum-stick-immunity-booster-capsules-natural-multivitamin-bottle-of-60-6.1-1687237315.jpg',
				face: 'side',
				sequence: '6.1',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/H62199/everherb-pharmeasy-moringa-drum-stick-immunity-booster-capsules-natural-multivitamin-bottle-of-60-6.2-1687237317.jpg',
				face: 'side',
				sequence: '6.2',
			},
		],
		labelDetails: null,
		ratingDetails: {
			count: 158,
			value: 3.9367088607594938,
		},
		productTierAttributes: {
			type: 5,
			text: 'Guaranteed Delivery',
		},
		productSubstitutionAttributes: null,
		productAvailabilityFlags: {
			isAvailable: true,
			showVariantsInBottomSheet: true,
			notifyMe: false,
		},
		maxQuantity: 20,
		productVolume: 0,
		similarProductsAttributes: null,
		minQuantity: 1,
		isAvailable: true,
		images: [
			'https://cdn01.pharmeasy.in/dam/products_otc/H62199/everherb-pharmeasy-moringa-drum-stick-immunity-booster-capsules-natural-multivitamin-bottle-of-60-2-1687237313.jpg?dim=300x0&f=jpg&dpr=3&q=60',
		],
		listingId: '14927809',
	},
	{
		productId: 3489646,
		name: 'Liveasy Wellness Pain Relief Balm 45gm',
		slug: 'liveasy-essential-pain-reliefbalm-3489646',
		manufacturer: 'LIVEASY',
		productType: 2,
		mrpDecimal: '115.00',
		salePriceDecimal: '109.25',
		discountDecimal: '5.75',
		discountPercent: '5',
		categoryId: null,
		damImages: [
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/C93509/liveasy-essential-pain-relief-balm-45gm-2-1659963202.jpg',
				face: 'front',
				sequence: '2',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/C93509/liveasy-essential-pain-relief-balm-45gm-6.1-1659963200.jpg',
				face: 'side',
				sequence: '6.1',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/C93509/liveasy-essential-pain-relief-balm-45gm-7-1659963198.jpg',
				face: 'back',
				sequence: '7',
			},
		],
		labelDetails: null,
		ratingDetails: {
			count: 89,
			value: 4.089887640449438,
		},
		productTierAttributes: {
			type: 5,
			text: 'Guaranteed Delivery',
		},
		productSubstitutionAttributes: null,
		productAvailabilityFlags: {
			isAvailable: true,
			showVariantsInBottomSheet: true,
			notifyMe: false,
		},
		maxQuantity: 20,
		productVolume: 0,
		similarProductsAttributes: null,
		minQuantity: 1,
		isAvailable: true,
		images: [
			'https://cdn01.pharmeasy.in/dam/products_otc/C93509/liveasy-essential-pain-relief-balm-45gm-2-1659963202.jpg?dim=300x0&f=jpg&dpr=3&q=60',
		],
		listingId: '14761853',
	},
	{
		productId: 3068258,
		name: 'Liveasy Essentials Adhesive Bandages - Box Of 100',
		slug: 'liveasy-essentials-adhesive-bandages---box-of-100-3068258',
		manufacturer: 'LIVEASY',
		productType: 2,
		mrpDecimal: '199.00',
		salePriceDecimal: '169.15',
		discountDecimal: '29.85',
		discountPercent: '15',
		categoryId: null,
		damImages: [
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/G19614/liveasy-essentials-adhesive-bandages-box-of-100-1-1641791579.jpg',
				face: 'box-front',
				sequence: '1',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/G19614/liveasy-essentials-adhesive-bandages-box-of-100-2-1641791583.jpg',
				face: 'front',
				sequence: '2',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/G19614/liveasy-essentials-adhesive-bandages-box-of-100-3-1641791587.jpg',
				face: 'combo',
				sequence: '3',
			},
		],
		labelDetails: null,
		ratingDetails: {
			count: 36,
			value: 4.027777777777778,
		},
		productTierAttributes: {
			type: 5,
			text: 'Guaranteed Delivery',
		},
		productSubstitutionAttributes: null,
		productAvailabilityFlags: {
			isAvailable: true,
			showVariantsInBottomSheet: true,
			notifyMe: false,
		},
		maxQuantity: 20,
		productVolume: 0,
		similarProductsAttributes: null,
		minQuantity: 1,
		isAvailable: true,
		images: [
			'https://cdn01.pharmeasy.in/dam/products_otc/G19614/liveasy-essentials-adhesive-bandages-box-of-100-1-1641791579.jpg?dim=300x0&f=jpg&dpr=3&q=60',
		],
		listingId: '14841015',
	},
	{
		productId: 3521591,
		name: 'Everherb (By Pharmeasy) Ashwagandha-Immunity Booster Capsules-Anxiety & Stress Relief - Bottle Of 90',
		slug: 'everherb-aswagandha-90-caps-3521591',
		manufacturer: 'EVERHERB',
		productType: 2,
		mrpDecimal: '799.00',
		salePriceDecimal: '407.49',
		discountDecimal: '391.51',
		discountPercent: '49',
		categoryId: null,
		damImages: [
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/P54860/everherb-by-pharmeasy-ashwagandha-immunity-booster-capsules-anxiety-stress-relief-bottle-of-90-2-1689585851.jpg',
				face: 'front',
				sequence: '2',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/P54860/everherb-by-pharmeasy-ashwagandha-immunity-booster-capsules-anxiety-stress-relief-bottle-of-90-6.1-1689585812.jpg',
				face: 'side',
				sequence: '6.1',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/P54860/everherb-by-pharmeasy-ashwagandha-immunity-booster-capsules-anxiety-stress-relief-bottle-of-90-6.2-1689585802.jpg',
				face: 'side',
				sequence: '6.2',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/P54860/everherb-by-pharmeasy-ashwagandha-immunity-booster-capsules-anxiety-stress-relief-bottle-of-90-6.3-1689585841.jpg',
				face: 'side',
				sequence: '6.3',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/P54860/everherb-by-pharmeasy-ashwagandha-immunity-booster-capsules-anxiety-stress-relief-bottle-of-90-6.4-1689585812.jpg',
				face: 'side',
				sequence: '6.4',
			},
		],
		labelDetails: null,
		ratingDetails: {
			count: 100,
			value: 4.08,
		},
		productTierAttributes: {
			type: 5,
			text: 'Guaranteed Delivery',
		},
		productSubstitutionAttributes: null,
		productAvailabilityFlags: {
			isAvailable: true,
			showVariantsInBottomSheet: true,
			notifyMe: false,
		},
		maxQuantity: 20,
		productVolume: 0,
		similarProductsAttributes: null,
		minQuantity: 1,
		isAvailable: true,
		images: [
			'https://cdn01.pharmeasy.in/dam/products_otc/P54860/everherb-by-pharmeasy-ashwagandha-immunity-booster-capsules-anxiety-stress-relief-bottle-of-90-2-1689585851.jpg?dim=300x0&f=jpg&dpr=3&q=60',
		],
		listingId: '15217588',
	},
	{
		productId: 3555033,
		name: 'Liveasy Wellness Anti Fungal Dusting Powder 100gm',
		slug: 'liveasy-wellness-dusting-powder-3555033',
		manufacturer: 'LIVEASY',
		productType: 2,
		mrpDecimal: '90.00',
		salePriceDecimal: '83.70',
		discountDecimal: '6.30',
		discountPercent: '7',
		categoryId: null,
		damImages: [
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/X65262/liveasy-wellness-anti-fungal-dusting-powder-100gm-6.1-1695722171.jpg',
				face: 'side',
				sequence: '6.1',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/X65262/liveasy-wellness-anti-fungal-dusting-powder-100gm-6.2-1695722132.jpg',
				face: 'side',
				sequence: '6.2',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/X65262/liveasy-wellness-anti-fungal-dusting-powder-100gm-6.3-1695722134.jpg',
				face: 'side',
				sequence: '6.3',
			},
		],
		labelDetails: null,
		ratingDetails: {
			count: 52,
			value: 3.9615384615384617,
		},
		productTierAttributes: {
			type: 5,
			text: 'Guaranteed Delivery',
		},
		productSubstitutionAttributes: null,
		productAvailabilityFlags: {
			isAvailable: true,
			showVariantsInBottomSheet: true,
			notifyMe: false,
		},
		maxQuantity: 20,
		productVolume: 0,
		similarProductsAttributes: null,
		minQuantity: 1,
		isAvailable: true,
		images: [
			'https://cdn01.pharmeasy.in/dam/products_otc/X65262/liveasy-wellness-anti-fungal-dusting-powder-100gm-6.1-1695722171.jpg?dim=300x0&f=jpg&dpr=3&q=60',
		],
		listingId: '14922322',
	},
	{
		productId: 237412,
		name: 'Everherb (By Pharmeasy) Karela - Blood Sugar Control - Lowers Bad Cholestrol - Bottle Of 60',
		slug: 'everherb-karela---blood-sugar-control---lowers-bad-cholestrol---bottle-of-60-237412',
		manufacturer: 'EVERHERB',
		productType: 2,
		mrpDecimal: '599.00',
		salePriceDecimal: '305.49',
		discountDecimal: '293.51',
		discountPercent: '49',
		categoryId: null,
		damImages: [
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/B55847/everherb-by-pharmeasy-karela-blood-sugar-control-lowers-bad-cholestrol-bottle-of-60-2-1661760071.jpg',
				face: 'front',
				sequence: '2',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/B55847/everherb-by-pharmeasy-karela-blood-sugar-control-lowers-bad-cholestrol-bottle-of-60-6.1-1661760129.jpg',
				face: 'side',
				sequence: '6.1',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/B55847/everherb-by-pharmeasy-karela-blood-sugar-control-lowers-bad-cholestrol-bottle-of-60-6.2-1661760099.jpg',
				face: 'side',
				sequence: '6.2',
			},
		],
		labelDetails: {
			code: 3,
			name: 'FEATURED',
		},
		ratingDetails: {
			count: 140,
			value: 4.071428571428571,
		},
		productTierAttributes: {
			type: 5,
			text: 'Guaranteed Delivery',
		},
		productSubstitutionAttributes: null,
		productAvailabilityFlags: {
			isAvailable: true,
			showVariantsInBottomSheet: true,
			notifyMe: false,
		},
		maxQuantity: 20,
		productVolume: 0,
		similarProductsAttributes: null,
		minQuantity: 1,
		isAvailable: true,
		images: [
			'https://cdn01.pharmeasy.in/dam/products_otc/B55847/everherb-by-pharmeasy-karela-blood-sugar-control-lowers-bad-cholestrol-bottle-of-60-2-1661760071.jpg?dim=300x0&f=jpg&dpr=3&q=60',
		],
		listingId: '15200033',
	},
	{
		productId: 237410,
		name: 'Everherb (By Pharmeasy) Neem - Immunity Booster - Hair & Skin Detoxifier - Bottle Of 60',
		slug: 'everherb-neem---immunity-booster---skin-body-detoxifier---bottle-of-60-237410',
		manufacturer: 'EVERHERB',
		productType: 2,
		mrpDecimal: '599.00',
		salePriceDecimal: '311.48',
		discountDecimal: '287.52',
		discountPercent: '48',
		categoryId: null,
		damImages: [
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/D41806/everherb-by-pharmeasy-neem-immunity-booster-hair-skin-detoxifier-bottle-of-60-2-1672128436.jpg',
				face: 'front',
				sequence: '2',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/D41806/everherb-by-pharmeasy-neem-immunity-booster-hair-skin-detoxifier-bottle-of-60-6.1-1672128434.jpg',
				face: 'side',
				sequence: '6.1',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/D41806/everherb-by-pharmeasy-neem-immunity-booster-hair-skin-detoxifier-bottle-of-60-6.2-1672128440.jpg',
				face: 'side',
				sequence: '6.2',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/D41806/everherb-by-pharmeasy-neem-immunity-booster-hair-skin-detoxifier-bottle-of-60-6.3-1672128438.jpg',
				face: 'side',
				sequence: '6.3',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/D41806/everherb-by-pharmeasy-neem-immunity-booster-hair-skin-detoxifier-bottle-of-60-6.4-1672128432.jpg',
				face: 'side',
				sequence: '6.4',
			},
		],
		labelDetails: {
			code: 3,
			name: 'FEATURED',
		},
		ratingDetails: {
			count: 121,
			value: 3.809917355371901,
		},
		productTierAttributes: {
			type: 5,
			text: 'Guaranteed Delivery',
		},
		productSubstitutionAttributes: null,
		productAvailabilityFlags: {
			isAvailable: true,
			showVariantsInBottomSheet: true,
			notifyMe: false,
		},
		maxQuantity: 20,
		productVolume: 0,
		similarProductsAttributes: null,
		minQuantity: 1,
		isAvailable: true,
		images: [
			'https://cdn01.pharmeasy.in/dam/products_otc/D41806/everherb-by-pharmeasy-neem-immunity-booster-hair-skin-detoxifier-bottle-of-60-2-1672128436.jpg?dim=300x0&f=jpg&dpr=3&q=60',
		],
		listingId: '15100786',
	},
	{
		productId: 3110917,
		name: 'Liveasy Essentials Bamboo Cotton Buds - 80 Sticks/160 Swabs',
		slug: 'liveasy-essentials-bamboo-cotton-swabs-3110917',
		manufacturer: 'LIVEASY',
		productType: 2,
		mrpDecimal: '65.00',
		salePriceDecimal: '61.75',
		discountDecimal: '3.25',
		discountPercent: '5',
		categoryId: null,
		damImages: [
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/A65047/liveasy-essentials-bamboo-cotton-buds-80-sticks-160-swabs-1-1705999231.jpg',
				face: 'box-front',
				sequence: '1',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/A65047/liveasy-essentials-bamboo-cotton-buds-80-sticks-160-swabs-3-1705999227.jpg',
				face: 'combo',
				sequence: '3',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/A65047/liveasy-essentials-bamboo-cotton-buds-80-sticks-160-swabs-4-1705999229.jpg',
				face: 'box-back',
				sequence: '4',
			},
		],
		labelDetails: null,
		ratingDetails: {
			count: 139,
			value: 3.5107913669064748,
		},
		productTierAttributes: {
			type: 5,
			text: 'Guaranteed Delivery',
		},
		productSubstitutionAttributes: null,
		productAvailabilityFlags: {
			isAvailable: true,
			showVariantsInBottomSheet: true,
			notifyMe: false,
		},
		maxQuantity: 20,
		productVolume: 0,
		similarProductsAttributes: null,
		minQuantity: 1,
		isAvailable: true,
		images: [
			'https://cdn01.pharmeasy.in/dam/products_otc/A65047/liveasy-essentials-bamboo-cotton-buds-80-sticks-160-swabs-1-1705999231.jpg?dim=300x0&f=jpg&dpr=3&q=60',
		],
		listingId: '14727919',
	},
	{
		productId: 2935249,
		name: 'Liveasy Essentials Tongue Cleaner (Pack Of 2)',
		slug: 'liveasy-essentials-tongue-cleaner-pack-of-2--2935249',
		manufacturer: 'LIVEASY',
		productType: 2,
		mrpDecimal: '99.00',
		salePriceDecimal: '94.05',
		discountDecimal: '4.95',
		discountPercent: '5',
		categoryId: null,
		damImages: [
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/H12065/liveasy-essentials-tongue-cleaner-pack-of-2-1-1654256934.jpg',
				face: 'box-front',
				sequence: '1',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/H12065/liveasy-essentials-tongue-cleaner-pack-of-2-2-1654256949.jpg',
				face: 'front',
				sequence: '2',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/H12065/liveasy-essentials-tongue-cleaner-pack-of-2-3-1654256895.jpg',
				face: 'combo',
				sequence: '3',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/H12065/liveasy-essentials-tongue-cleaner-pack-of-2-4-1654256916.jpg',
				face: 'box-back',
				sequence: '4',
			},
		],
		labelDetails: null,
		ratingDetails: {
			count: 122,
			value: 3.5737704918032787,
		},
		productTierAttributes: {
			type: 5,
			text: 'Guaranteed Delivery',
		},
		productSubstitutionAttributes: null,
		productAvailabilityFlags: {
			isAvailable: true,
			showVariantsInBottomSheet: true,
			notifyMe: false,
		},
		maxQuantity: 20,
		productVolume: 0,
		similarProductsAttributes: null,
		minQuantity: 1,
		isAvailable: true,
		images: [
			'https://cdn01.pharmeasy.in/dam/products_otc/H12065/liveasy-essentials-tongue-cleaner-pack-of-2-1-1654256934.jpg?dim=300x0&f=jpg&dpr=3&q=60',
		],
		listingId: '14900469',
	},
	{
		productId: 4069006,
		name: 'Everherb Diabetic Care Juice-13 Potent Ingredients -Healthy Blood Sugar Management - 500 Ml Bottle',
		slug: 'everherb-diabetic-care-juice-13-potent-ingredients--healthy-blood-sugar-management---500-ml-bottle-4069006',
		manufacturer: 'EVERHERB',
		productType: 2,
		mrpDecimal: '299.00',
		salePriceDecimal: '149.50',
		discountDecimal: '149.50',
		discountPercent: '50',
		categoryId: null,
		damImages: [
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/H29530/everherb-diabetic-care-juice-13-potent-ingredients-healthy-blood-sugar-management-500-ml-bottle-2-1698903599.jpg',
				face: 'front',
				sequence: '2',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/H29530/everherb-diabetic-care-juice-13-potent-ingredients-healthy-blood-sugar-management-500-ml-bottle-6.1-1698903519.jpg',
				face: 'side',
				sequence: '6.1',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/H29530/everherb-diabetic-care-juice-13-potent-ingredients-healthy-blood-sugar-management-500-ml-bottle-6.2-1698903532.jpg',
				face: 'side',
				sequence: '6.2',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/H29530/everherb-diabetic-care-juice-13-potent-ingredients-healthy-blood-sugar-management-500-ml-bottle-6.3-1698903560.jpg',
				face: 'side',
				sequence: '6.3',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/H29530/everherb-diabetic-care-juice-13-potent-ingredients-healthy-blood-sugar-management-500-ml-bottle-6.4-1698903656.jpg',
				face: 'side',
				sequence: '6.4',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/H29530/everherb-diabetic-care-juice-13-potent-ingredients-healthy-blood-sugar-management-500-ml-bottle-6.5-1698903574.jpg',
				face: 'side',
				sequence: '6.5',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/H29530/everherb-diabetic-care-juice-13-potent-ingredients-healthy-blood-sugar-management-500-ml-bottle-6.6-1698903656.jpg',
				face: 'side',
				sequence: '6.6',
			},
		],
		labelDetails: null,
		ratingDetails: {
			count: 5,
			value: 2.8,
		},
		productTierAttributes: {
			type: 5,
			text: 'Guaranteed Delivery',
		},
		productSubstitutionAttributes: null,
		productAvailabilityFlags: {
			isAvailable: true,
			showVariantsInBottomSheet: true,
			notifyMe: false,
		},
		maxQuantity: 20,
		productVolume: 0,
		similarProductsAttributes: null,
		minQuantity: 1,
		isAvailable: true,
		images: [
			'https://cdn01.pharmeasy.in/dam/products_otc/H29530/everherb-diabetic-care-juice-13-potent-ingredients-healthy-blood-sugar-management-500-ml-bottle-2-1698903599.jpg?dim=300x0&f=jpg&dpr=3&q=60',
		],
		listingId: '19095938',
	},
	{
		productId: 3864230,
		name: 'Pharmeasy Joint Support - Maintains Joints Mobility - Bone & Joint Health - Bottle Of 60',
		slug: 'pharmeasy-joint-support---maintains-joints-mobility---bone-joint-health---bottle-of-60-3864230',
		manufacturer: 'PHARMEASY',
		productType: 2,
		mrpDecimal: '799.00',
		salePriceDecimal: '399.50',
		discountDecimal: '399.50',
		discountPercent: '50',
		categoryId: null,
		damImages: [
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/B19345/pharmeasy-joint-support-maintains-joints-mobility-bone-joint-health-bottle-of-60-2-1698644927.jpg',
				face: 'front',
				sequence: '2',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/B19345/pharmeasy-joint-support-maintains-joints-mobility-bone-joint-health-bottle-of-60-6.1-1698644967.jpg',
				face: 'side',
				sequence: '6.1',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/B19345/pharmeasy-joint-support-maintains-joints-mobility-bone-joint-health-bottle-of-60-6.2-1698644943.jpg',
				face: 'side',
				sequence: '6.2',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/B19345/pharmeasy-joint-support-maintains-joints-mobility-bone-joint-health-bottle-of-60-6.3-1698644983.jpg',
				face: 'side',
				sequence: '6.3',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/B19345/pharmeasy-joint-support-maintains-joints-mobility-bone-joint-health-bottle-of-60-6.4-1699510654.jpg',
				face: 'side',
				sequence: '6.4',
			},
		],
		labelDetails: null,
		ratingDetails: {
			count: 41,
			value: 3.6341463414634148,
		},
		productTierAttributes: {
			type: 5,
			text: 'Guaranteed Delivery',
		},
		productSubstitutionAttributes: null,
		productAvailabilityFlags: {
			isAvailable: true,
			showVariantsInBottomSheet: true,
			notifyMe: false,
		},
		maxQuantity: 20,
		productVolume: 0,
		similarProductsAttributes: null,
		minQuantity: 1,
		isAvailable: true,
		images: [
			'https://cdn01.pharmeasy.in/dam/products_otc/B19345/pharmeasy-joint-support-maintains-joints-mobility-bone-joint-health-bottle-of-60-2-1698644927.jpg?dim=300x0&f=jpg&dpr=3&q=60',
		],
		listingId: '15048134',
	},
	{
		productId: 3624650,
		name: 'Liveasy Wellness Pain Relief Gel Tube Of 30 G',
		slug: 'liveasy-wellness-pain-relief-gel-3624650',
		manufacturer: 'LIVEASY',
		productType: 2,
		mrpDecimal: '99.00',
		salePriceDecimal: '94.05',
		discountDecimal: '4.95',
		discountPercent: '5',
		categoryId: null,
		damImages: [
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/A25289/liveasy-wellness-pain-relief-gel-tube-of-30-g-1-1659962889.jpg',
				face: 'box-front',
				sequence: '1',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/A25289/liveasy-wellness-pain-relief-gel-tube-of-30-g-2-1659962891.jpg',
				face: 'front',
				sequence: '2',
			},
		],
		labelDetails: null,
		ratingDetails: {
			count: 39,
			value: 3.8205128205128207,
		},
		productTierAttributes: {
			type: 5,
			text: 'Guaranteed Delivery',
		},
		productSubstitutionAttributes: null,
		productAvailabilityFlags: {
			isAvailable: true,
			showVariantsInBottomSheet: true,
			notifyMe: false,
		},
		maxQuantity: 20,
		productVolume: 0,
		similarProductsAttributes: null,
		minQuantity: 1,
		isAvailable: true,
		images: [
			'https://cdn01.pharmeasy.in/dam/products_otc/A25289/liveasy-wellness-pain-relief-gel-tube-of-30-g-1-1659962889.jpg?dim=300x0&f=jpg&dpr=3&q=60',
		],
		listingId: '14971208',
	},
	{
		productId: 3624537,
		name: "Liveasy Essentials Cleansing Aloe Vera Refreshing Lime Facial Wipes 20'S",
		slug: 'liveasy-essentials-aloe-vera-refreshing-and-cleansing-face-wipes-20-s-3624537',
		manufacturer: 'LIVEASY',
		productType: 2,
		mrpDecimal: '69.00',
		salePriceDecimal: '62.10',
		discountDecimal: '6.90',
		discountPercent: '10',
		categoryId: null,
		damImages: [
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/N65859/liveasy-essentials-cleansing-aloe-vera-refreshing-lime-facial-wipes-20s-2-1697177802.jpg',
				face: 'front',
				sequence: '2',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/N65859/liveasy-essentials-cleansing-aloe-vera-refreshing-lime-facial-wipes-20s-6.1-1697177806.jpg',
				face: 'side',
				sequence: '6.1',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/N65859/liveasy-essentials-cleansing-aloe-vera-refreshing-lime-facial-wipes-20s-7-1697177804.jpg',
				face: 'back',
				sequence: '7',
			},
		],
		labelDetails: null,
		ratingDetails: {
			count: 24,
			value: 4.375,
		},
		productTierAttributes: {
			type: 5,
			text: 'Guaranteed Delivery',
		},
		productSubstitutionAttributes: null,
		productAvailabilityFlags: {
			isAvailable: true,
			showVariantsInBottomSheet: true,
			notifyMe: false,
		},
		maxQuantity: 20,
		productVolume: 0,
		similarProductsAttributes: null,
		minQuantity: 1,
		isAvailable: true,
		images: [
			'https://cdn01.pharmeasy.in/dam/products_otc/N65859/liveasy-essentials-cleansing-aloe-vera-refreshing-lime-facial-wipes-20s-2-1697177802.jpg?dim=300x0&f=jpg&dpr=3&q=60',
		],
		listingId: '14958587',
	},
	{
		productId: 2935288,
		name: 'Liveasy Essentials Pill Box',
		slug: 'liveasy-essentials-pill-box-2935288',
		manufacturer: 'LIVEASY',
		productType: 2,
		mrpDecimal: '399.00',
		salePriceDecimal: '279.30',
		discountDecimal: '119.70',
		discountPercent: '30',
		categoryId: null,
		damImages: [
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/Y53636/liveasy-essentials-pill-box-2-1654233076.jpg',
				face: 'front',
				sequence: '2',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/Y53636/liveasy-essentials-pill-box-3-1654232988.jpg',
				face: 'combo',
				sequence: '3',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/Y53636/liveasy-essentials-pill-box-6.1-1654232986.jpg',
				face: 'side',
				sequence: '6.1',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/Y53636/liveasy-essentials-pill-box-6.2-1654233017.jpg',
				face: 'side',
				sequence: '6.2',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/Y53636/liveasy-essentials-pill-box-6.3-1654232982.jpg',
				face: 'side',
				sequence: '6.3',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/Y53636/liveasy-essentials-pill-box-6.4-1654232989.jpg',
				face: 'side',
				sequence: '6.4',
			},
		],
		labelDetails: null,
		ratingDetails: {
			count: 175,
			value: 3.4285714285714284,
		},
		productTierAttributes: {
			type: 5,
			text: 'Guaranteed Delivery',
		},
		productSubstitutionAttributes: null,
		productAvailabilityFlags: {
			isAvailable: true,
			showVariantsInBottomSheet: true,
			notifyMe: false,
		},
		maxQuantity: 20,
		productVolume: 0,
		similarProductsAttributes: null,
		minQuantity: 1,
		isAvailable: true,
		images: [
			'https://cdn01.pharmeasy.in/dam/products_otc/Y53636/liveasy-essentials-pill-box-2-1654233076.jpg?dim=300x0&f=jpg&dpr=3&q=60',
		],
		listingId: '14670655',
	},
	{
		productId: 3662202,
		name: 'Pharmeasy Multivitamin Women - Overall Women Wellness - Builds Immunity - Bottle Of 60',
		slug: 'pharmeasy-multivitamin-women---bottle-of-60-3662202',
		manufacturer: 'PHARMEASY',
		productType: 2,
		mrpDecimal: '799.00',
		salePriceDecimal: '407.49',
		discountDecimal: '391.51',
		discountPercent: '49',
		categoryId: null,
		damImages: [
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/R76285/pharmeasy-multivitamin-women-overall-women-wellness-builds-immunity-bottle-of-60-2-1675775228.jpg',
				face: 'front',
				sequence: '2',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/R76285/pharmeasy-multivitamin-women-overall-women-wellness-builds-immunity-bottle-of-60-6.1-1675775237.jpg',
				face: 'side',
				sequence: '6.1',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/R76285/pharmeasy-multivitamin-women-overall-women-wellness-builds-immunity-bottle-of-60-6.2-1675775228.jpg',
				face: 'side',
				sequence: '6.2',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/R76285/pharmeasy-multivitamin-women-overall-women-wellness-builds-immunity-bottle-of-60-6.3-1699510424.jpg',
				face: 'side',
				sequence: '6.3',
			},
		],
		labelDetails: null,
		ratingDetails: {
			count: 19,
			value: 4.421052631578948,
		},
		productTierAttributes: {
			type: 5,
			text: 'Guaranteed Delivery',
		},
		productSubstitutionAttributes: null,
		productAvailabilityFlags: {
			isAvailable: true,
			showVariantsInBottomSheet: true,
			notifyMe: false,
		},
		maxQuantity: 20,
		productVolume: 0,
		similarProductsAttributes: null,
		minQuantity: 1,
		isAvailable: true,
		images: [
			'https://cdn01.pharmeasy.in/dam/products_otc/R76285/pharmeasy-multivitamin-women-overall-women-wellness-builds-immunity-bottle-of-60-2-1675775228.jpg?dim=300x0&f=jpg&dpr=3&q=60',
		],
		listingId: '14710738',
	},
	{
		productId: 234977,
		name: "Everherb (By Pharmeasy) Men'S Formula-Blend Of Powerful Herb-Increase Sperm Count-Bottle Of 60",
		slug: 'everherb-men-s-formula---blend-of-6-safe-powerful-herb---increase-sperm-count---bottle-of-60-234977',
		manufacturer: 'EVERHERB',
		productType: 2,
		mrpDecimal: '999.00',
		salePriceDecimal: '499.50',
		discountDecimal: '499.50',
		discountPercent: '50',
		categoryId: null,
		damImages: [
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/N51273/everherb-by-pharmeasy-mens-formula-blend-of-powerful-herb-increase-sperm-count-bottle-of-60-2-1689582878.jpg',
				face: 'front',
				sequence: '2',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/N51273/everherb-by-pharmeasy-mens-formula-blend-of-powerful-herb-increase-sperm-count-bottle-of-60-6.1-1689582869.jpg',
				face: 'side',
				sequence: '6.1',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/N51273/everherb-by-pharmeasy-mens-formula-blend-of-powerful-herb-increase-sperm-count-bottle-of-60-6.2-1689582920.jpg',
				face: 'side',
				sequence: '6.2',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/N51273/everherb-by-pharmeasy-mens-formula-blend-of-powerful-herb-increase-sperm-count-bottle-of-60-6.3-1689582949.jpg',
				face: 'side',
				sequence: '6.3',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/N51273/everherb-by-pharmeasy-mens-formula-blend-of-powerful-herb-increase-sperm-count-bottle-of-60-6.4-1689582870.jpg',
				face: 'side',
				sequence: '6.4',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/N51273/everherb-by-pharmeasy-mens-formula-blend-of-powerful-herb-increase-sperm-count-bottle-of-60-6.5-1689582920.jpg',
				face: 'side',
				sequence: '6.5',
			},
		],
		labelDetails: {
			code: 2,
			name: 'RECOMMENDED',
		},
		ratingDetails: {
			count: 165,
			value: 3.6363636363636362,
		},
		productTierAttributes: {
			type: 5,
			text: 'Guaranteed Delivery',
		},
		productSubstitutionAttributes: null,
		productAvailabilityFlags: {
			isAvailable: true,
			showVariantsInBottomSheet: true,
			notifyMe: false,
		},
		maxQuantity: 20,
		productVolume: 0,
		similarProductsAttributes: null,
		minQuantity: 1,
		isAvailable: true,
		images: [
			'https://cdn01.pharmeasy.in/dam/products_otc/N51273/everherb-by-pharmeasy-mens-formula-blend-of-powerful-herb-increase-sperm-count-bottle-of-60-2-1689582878.jpg?dim=300x0&f=jpg&dpr=3&q=60',
		],
		listingId: '14876817',
	},
	{
		productId: 3580866,
		name: 'Liveasy Wellness Diabetic Protein Powder Chocolate Flavour 400g',
		slug: 'liveasy-wellness-diabetic-protein-powder-chocolate-flavour-400g-3580866',
		manufacturer: 'LIVEASY',
		productType: 2,
		mrpDecimal: '999.00',
		salePriceDecimal: '539.46',
		discountDecimal: '459.54',
		discountPercent: '46',
		categoryId: null,
		damImages: [
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/H14523/liveasy-wellness-diabetic-protein-powder-chocolate-flavour-400g-2-1671742949.jpg',
				face: 'front',
				sequence: '2',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/H14523/liveasy-wellness-diabetic-protein-powder-chocolate-flavour-400g-6.1-1671742947.jpg',
				face: 'side',
				sequence: '6.1',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/H14523/liveasy-wellness-diabetic-protein-powder-chocolate-flavour-400g-7-1671742945.jpg',
				face: 'back',
				sequence: '7',
			},
		],
		labelDetails: null,
		ratingDetails: {
			count: 120,
			value: 4.241666666666666,
		},
		productTierAttributes: {
			type: 5,
			text: 'Guaranteed Delivery',
		},
		productSubstitutionAttributes: null,
		productAvailabilityFlags: {
			isAvailable: true,
			showVariantsInBottomSheet: true,
			notifyMe: false,
		},
		maxQuantity: 20,
		productVolume: 0,
		similarProductsAttributes: null,
		minQuantity: 1,
		isAvailable: true,
		images: [
			'https://cdn01.pharmeasy.in/dam/products_otc/H14523/liveasy-wellness-diabetic-protein-powder-chocolate-flavour-400g-2-1671742949.jpg?dim=300x0&f=jpg&dpr=3&q=60',
		],
		listingId: '14719330',
	},
	{
		productId: 3134595,
		name: 'Pharmeasy Orthopaedic Electric Heat Belt Regular',
		slug: 'pharmeasy-orthopaedic-electric-heat-belt-regular-3134595',
		manufacturer: 'PHARMEASY',
		productType: 2,
		mrpDecimal: '949.00',
		salePriceDecimal: '569.40',
		discountDecimal: '379.60',
		discountPercent: '40',
		categoryId: null,
		damImages: [
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/E16289/pharmeasy-orthopaedic-electric-heat-belt-regular-2-1671742418.jpg',
				face: 'front',
				sequence: '2',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/E16289/pharmeasy-orthopaedic-electric-heat-belt-regular-3-1671742416.jpg',
				face: 'combo',
				sequence: '3',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/E16289/pharmeasy-orthopaedic-electric-heat-belt-regular-6.1-1671742407.jpg',
				face: 'side',
				sequence: '6.1',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/E16289/pharmeasy-orthopaedic-electric-heat-belt-regular-6.2-1671742413.jpg',
				face: 'side',
				sequence: '6.2',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/E16289/pharmeasy-orthopaedic-electric-heat-belt-regular-7-1671742410.jpg',
				face: 'back',
				sequence: '7',
			},
		],
		labelDetails: {
			code: 5,
			name: 'ON SALE',
		},
		ratingDetails: {
			count: 83,
			value: 3.433734939759036,
		},
		productTierAttributes: {
			type: 5,
			text: 'Guaranteed Delivery',
		},
		productSubstitutionAttributes: null,
		productAvailabilityFlags: {
			isAvailable: true,
			showVariantsInBottomSheet: true,
			notifyMe: false,
		},
		maxQuantity: 20,
		productVolume: 0,
		similarProductsAttributes: null,
		minQuantity: 1,
		isAvailable: true,
		images: [
			'https://cdn01.pharmeasy.in/dam/products_otc/E16289/pharmeasy-orthopaedic-electric-heat-belt-regular-2-1671742418.jpg?dim=300x0&f=jpg&dpr=3&q=60',
		],
		listingId: '15048812',
	},
	{
		productId: 3491152,
		name: 'Pharmeasy Calcium Magnesium Vitamin D3 & Zinc - Bones & Dental Health - Bottle 120',
		slug: 'pharmeasy-calcium-magnesium-zinc-vitamin-d3---pack-of-120-3491152',
		manufacturer: 'PHARMEASY',
		productType: 2,
		mrpDecimal: '899.00',
		salePriceDecimal: '539.40',
		discountDecimal: '359.60',
		discountPercent: '40',
		categoryId: null,
		damImages: [
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/Q97636/pharmeasy-calcium-magnesium-vitamin-d3-zinc-bones-dental-health-bottle-120-2-1698645746.jpg',
				face: 'front',
				sequence: '2',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/Q97636/pharmeasy-calcium-magnesium-vitamin-d3-zinc-bones-dental-health-bottle-120-6.1-1698645772.jpg',
				face: 'side',
				sequence: '6.1',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/Q97636/pharmeasy-calcium-magnesium-vitamin-d3-zinc-bones-dental-health-bottle-120-6.3-1699510298.jpg',
				face: 'side',
				sequence: '6.3',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/Q97636/pharmeasy-calcium-magnesium-vitamin-d3-zinc-bones-dental-health-bottle-120-7-1671743163.jpg',
				face: 'back',
				sequence: '7',
			},
		],
		labelDetails: null,
		ratingDetails: {
			count: 68,
			value: 4.161764705882353,
		},
		productTierAttributes: {
			type: 5,
			text: 'Guaranteed Delivery',
		},
		productSubstitutionAttributes: null,
		productAvailabilityFlags: {
			isAvailable: true,
			showVariantsInBottomSheet: true,
			notifyMe: false,
		},
		maxQuantity: 20,
		productVolume: 0,
		similarProductsAttributes: null,
		minQuantity: 1,
		isAvailable: true,
		images: [
			'https://cdn01.pharmeasy.in/dam/products_otc/Q97636/pharmeasy-calcium-magnesium-vitamin-d3-zinc-bones-dental-health-bottle-120-2-1698645746.jpg?dim=300x0&f=jpg&dpr=3&q=60',
		],
		listingId: '14734805',
	},
	{
		productId: 3626268,
		name: 'Pharmeasy Multivitamin Gummies For Kids And Adults Lemon & Strawberry Flavour Bottle Of 30 Gummies',
		slug: 'pharmeasy-multivitamin-gummies-3626268',
		manufacturer: 'PHARMEASY',
		productType: 2,
		mrpDecimal: '499.00',
		salePriceDecimal: '249.50',
		discountDecimal: '249.50',
		discountPercent: '50',
		categoryId: null,
		damImages: [
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/E54733/pharmeasy-multivitamin-gummies-for-kids-and-adults-healthy-growth-immunity-bottle-of-30-2-1671743494.jpg',
				face: 'front',
				sequence: '2',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/E54733/pharmeasy-multivitamin-gummies-for-kids-and-adults-healthy-growth-immunity-bottle-of-30-6.1-1671743491.jpg',
				face: 'side',
				sequence: '6.1',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/E54733/pharmeasy-multivitamin-gummies-for-kids-and-adults-healthy-growth-immunity-bottle-of-30-6.2-1671743489.jpg',
				face: 'side',
				sequence: '6.2',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/E54733/pharmeasy-multivitamin-gummies-for-kids-and-adults-healthy-growth-immunity-bottle-of-30-6.3-1671743500.jpg',
				face: 'side',
				sequence: '6.3',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/E54733/pharmeasy-multivitamin-gummies-for-kids-and-adults-healthy-growth-immunity-bottle-of-30-6.4-1671743503.jpg',
				face: 'side',
				sequence: '6.4',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/E54733/pharmeasy-multivitamin-gummies-for-kids-and-adults-healthy-growth-immunity-bottle-of-30-6.5-1671743492.jpg',
				face: 'side',
				sequence: '6.5',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/E54733/pharmeasy-multivitamin-gummies-for-kids-and-adults-healthy-growth-immunity-bottle-of-30-6.6-1671743505.jpg',
				face: 'side',
				sequence: '6.6',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/E54733/pharmeasy-multivitamin-gummies-for-kids-and-adults-healthy-growth-immunity-bottle-of-30-6.7-1671743498.jpg',
				face: 'side',
				sequence: '6.7',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/E54733/pharmeasy-multivitamin-gummies-for-kids-and-adults-healthy-growth-immunity-bottle-of-30-6.8-1671743485.jpg',
				face: 'side',
				sequence: '6.8',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/E54733/pharmeasy-multivitamin-gummies-for-kids-and-adults-healthy-growth-immunity-bottle-of-30-6.9-1671743487.jpg',
				face: 'side',
				sequence: '6.9',
			},
			{
				url: 'https://cdn01.pharmeasy.in/dam/products_otc/E54733/pharmeasy-multivitamin-gummies-for-kids-and-adults-healthy-growth-immunity-bottle-of-30-7-1671743496.jpg',
				face: 'back',
				sequence: '7',
			},
		],
		labelDetails: null,
		ratingDetails: {
			count: 45,
			value: 4.044444444444444,
		},
		productTierAttributes: {
			type: 5,
			text: 'Guaranteed Delivery',
		},
		productSubstitutionAttributes: null,
		productAvailabilityFlags: {
			isAvailable: true,
			showVariantsInBottomSheet: true,
			notifyMe: false,
		},
		maxQuantity: 20,
		productVolume: 0,
		similarProductsAttributes: null,
		minQuantity: 1,
		isAvailable: true,
		images: [
			'https://cdn01.pharmeasy.in/dam/products_otc/E54733/pharmeasy-multivitamin-gummies-for-kids-and-adults-healthy-growth-immunity-bottle-of-30-2-1671743494.jpg?dim=300x0&f=jpg&dpr=3&q=60',
		],
		listingId: '14977192',
	},
];
